# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '15.6'
use_frameworks!

post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
          File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
          end
      end
  end

def commonframeworks
  
#  pod 'AlamofireObjectMapper'
#  pod 'ReachabilitySwift'
#  pod 'SMCloudServices'
#  pod 'IQKeyboardManager'
  pod 'SwiftLint'
  pod 'SkeletonView'
  pod 'BugfenderSDK'
  pod 'Split'
  pod 'FirebaseCrashlytics'
  pod 'FirebaseAnalytics'
  pod 'Dynatrace'
end

target 'TestGithubAction' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestGithubAction
  commonframeworks

end
